target 'Flixer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyApp
  # This pulls in the latest version of Alamofire >= 4.4 but less than 5.0.
 
  pod 'AlamofireImage', '~> 3.3'
  # Add additional dependencies

  
end